### ISSUE TITLE
Missing dependencies and can not connect to database

### ISSUE THREAD

**Issue by hunghp666** [fat-tire/floreantpos#17]
Hi 
I'm new to this project. Thanks for your effort on this.
I can build it with maven just fine, its running. Now I want to implement something new to this codebase.
I check out this source and try to run in Eclipse but show some errors:
1. Missing some dependencies as show in this screen shot

![Screenshot 2022-10-08 071817](https://user-images.githubusercontent.com/88605836/194677908-c0531cb3-2bfe-48e9-8aca-6c2c55585dd5.jpg)

3. When starting app it cannot connect to database. Do i need to manual add something to make it work. Thanks and brgs,

com.floreantpos.util.DatabaseConnectionException: org.hibernate.InstantiationException: could not instantiate test objectcom.floreantpos.model.ModifierGroup
ERROR: 08-Oct-2022 07:07:47: org.hibernate.InstantiationException: could not instantiate test objectcom.floreantpos.model.ModifierGroup
	at com.floreantpos.util.DatabaseUtil.initialize(DatabaseUtil.java:548)
	at com.floreantpos.main.Application.initializeSystem(Application.java:167)
	at com.floreantpos.main.Application.start(Application.java:135)
	at com.floreantpos.main.Main.main(Main.java:58)
Caused by: org.hibernate.InstantiationException: could not instantiate test objectcom.floreantpos.model.ModifierGroup
	at org.hibernate.engine.UnsavedValueFactory.instantiate(UnsavedValueFactory.java:25)
	at org.hibernate.engine.UnsavedValueFactory.getUnsavedIdentifierValue(UnsavedValueFactory.java:44)
	at org.hibernate.tuple.PropertyFactory.buildIdentifierProperty(PropertyFactory.java:44)
	at org.hibernate.tuple.entity.EntityMetamodel.<init>(EntityMetamodel.java:124)
	at org.hibernate.persister.entity.AbstractEntityPersister.<init>(AbstractEntityPersister.java:434)
	at org.hibernate.persister.entity.SingleTableEntityPersister.<init>(SingleTableEntityPersister.java:109)
	at org.hibernate.persister.PersisterFactory.createClassPersister(PersisterFactory.java:55)
	at org.hibernate.impl.SessionFactoryImpl.<init>(SessionFactoryImpl.java:226)
	at org.hibernate.cfg.Configuration.buildSessionFactory(Configuration.java:1300)
	at com.floreantpos.model.dao._RootDAO.reInitialize(_RootDAO.java:260)
	at com.floreantpos.util.DatabaseUtil.initialize(DatabaseUtil.java:544)
	... 3 more
Caused by: java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:480)
	at org.hibernate.engine.UnsavedValueFactory.instantiate(UnsavedValueFactory.java:22)
	... 13 more
Caused by: java.lang.Error: Unresolved compilation problems: 
	The import javax.xml.bind cannot be resolved
	XmlRootElement cannot be resolved to a type

	at com.floreantpos.model.ModifierGroup.<init>(ModifierGroup.java:3)
	... 19 more
ERROR: 08-Oct-2022 07:07:47: com.floreantpos.util.DatabaseConnectionException: org.hibernate.InstantiationException: could not instantiate test objectcom.floreantpos.model.ModifierGroup

**Comment by fat-tire** [comment]
Hmm.  Im' not sure.  I believe there have been more updates to the floreant code upstream that aren't in this git repo-- did you check there to see if there's any fix?

**Comment by hunghp666** [comment]
Thanks. I tried with original repo. It stills show errors but I can build it with no problem. Maybe I'm missing some IDE configurations.
